site_name: Optimization Tutorial
docs_dir: docs
site_url: https://optimization-tutorial.com/

repo_url: https://github.com/SimonBlanke/optimization-tutorial
edit_uri: ""

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square
  palette:
    primary: indigo
    accent: deep purple

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra_css:
  - css/extra.css


extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Overview: overview.md

  - Optimization Algorithms:
    - Local:
      - Hill Climbing: optimizers/hill_climbing.md
      - Stochastic Hill Climbing: optimizers/stochastic_hill_climbing.md
      - Simulated Annealing: optimizers/simulated_annealing.md
      - Pattern Search: optimizers/pattern_search.md
      - Powell's Method: optimizers/powells_method.md
      - Downhill Simplex Optimization: optimizers/downhill_simplex.md

    - Global:
      - Random Search: optimizers/random_search.md
      - Grid Search: optimizers/grid_search.md
      - Random Restart Hill Climbing: optimizers/random_restart_hill_climbing.md

    - Population:
      - Parallel Tempering: optimizers/parallel_tempering.md
      - Particle Swarm Optimization: optimizers/particle_swarm_optimization.md
      - Evolution Strategy: optimizers/evolution_strategy.md

    - Sequential:
      - Bayesian Optimization: optimizers/bayesian_optimization.md
      - Tree Structured Parzen Estimators: optimizers/tree_structured_parzen_estimators.md
      - Forest Optimization: optimizers/forest_optimization.md

  - Experimental Algorithms:
    - Local:
      - Repulsing Hill Climbing: experimental/repulsing_hill_climbing.md

    - Global:
      - Random Annealing: experimental/random_annealing.md
